import { MusicTrack } from '../types';

export const MUSIC_TRACKS: MusicTrack[] = [
  {
    id: 'music-piano-dawn',
    title: 'Piano ao amanhecer',
    artist: 'Respira Instrumental',
    category: 'meditate',
    categoryLabel: 'Para meditar',
    durationMinutes: 5,
    durationSeconds: 300,
    audioUrl: 'https://cdn.pixabay.com/download/audio/2022/01/18/audio_7240c9f131.mp3?filename=gentle-piano-calm-6893.mp3',
    thumbnailUrl: 'https://images.unsplash.com/photo-1520523839898-50712825d3a3?auto=format&fit=crop&w=600&q=80',
    accentColor: '#4A6B82',
    description: 'Acordes serenos e compassados de piano acústico para abrir o dia com clareza e presença.',
  },
  {
    id: 'music-quiet-night',
    title: 'Noite tranquila',
    artist: 'Respira Instrumental',
    category: 'sleep',
    categoryLabel: 'Para dormir',
    durationMinutes: 8,
    durationSeconds: 480,
    audioUrl: 'https://cdn.pixabay.com/download/audio/2022/04/27/audio_93818f9cf0.mp3?filename=ambient-pad-serenity-110294.mp3',
    thumbnailUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=600&q=80',
    accentColor: '#2B3D54',
    description: 'Camadas harmônicas suaves e etéreas que diminuem o ritmo cardíaco e preparam para o descanso.',
  },
  {
    id: 'music-serene-path',
    title: 'Caminho sereno',
    artist: 'Respira Instrumental',
    category: 'relax',
    categoryLabel: 'Para relaxar',
    durationMinutes: 6,
    durationSeconds: 360,
    audioUrl: 'https://cdn.pixabay.com/download/audio/2022/05/16/audio_c9769ee80a.mp3?filename=soft-ambient-pad-12345.mp3',
    thumbnailUrl: 'https://images.unsplash.com/photo-1470240731273-7821a6eeb6bd?auto=format&fit=crop&w=600&q=80',
    accentColor: '#3B7A57',
    description: 'Melodia relaxante de cordas e sintetizadores sutis para aliviar o peso de um dia agitado.',
  },
  {
    id: 'music-breath-pause',
    title: 'Pausa para respirar',
    artist: 'Respira Instrumental',
    category: 'pause',
    categoryLabel: 'Para uma pausa',
    durationMinutes: 4,
    durationSeconds: 240,
    audioUrl: 'https://cdn.pixabay.com/download/audio/2022/01/18/audio_d0a13f69d2.mp3?filename=gentle-acoustic-guitar-7890.mp3',
    thumbnailUrl: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=600&q=80',
    accentColor: '#247B74',
    description: 'Arpejos leves de violão acústico para fazer uma pausa de poucos minutos e renovar o ânimo.',
  },
  {
    id: 'music-morning-light',
    title: 'Luz da manhã',
    artist: 'Respira Instrumental',
    category: 'decelerate',
    categoryLabel: 'Para desacelerar',
    durationMinutes: 5,
    durationSeconds: 300,
    audioUrl: 'https://cdn.pixabay.com/download/audio/2021/08/04/audio_32b03657b9.mp3?filename=morning-breeze-music-6543.mp3',
    thumbnailUrl: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=600&q=80',
    accentColor: '#5B8C5A',
    description: 'Textura harmônica luminosa para desacelerar pensamentos e reencontrar o equilíbrio.',
  },
  {
    id: 'music-silent-sky',
    title: 'Céu silencioso',
    artist: 'Respira Instrumental',
    category: 'meditate',
    categoryLabel: 'Para meditar',
    durationMinutes: 7,
    durationSeconds: 420,
    audioUrl: 'https://cdn.pixabay.com/download/audio/2022/03/15/audio_c3c3a9926e.mp3?filename=meditation-bowl-drone-10925.mp3',
    thumbnailUrl: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=600&q=80',
    accentColor: '#534666',
    description: 'Tons de taças tibetanas e ressonâncias profundas para momentos de interiorização e silêncio.',
  },
  {
    id: 'music-soft-focus',
    title: 'Concentração suave',
    artist: 'Respira Instrumental',
    category: 'study',
    categoryLabel: 'Para estudar',
    durationMinutes: 10,
    durationSeconds: 600,
    audioUrl: 'https://cdn.pixabay.com/download/audio/2022/10/14/audio_993e506699.mp3?filename=lofi-study-ambient-1234.mp3',
    thumbnailUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=600&q=80',
    accentColor: '#7A6248',
    description: 'Pulso rítmico suave e harmonia contínua para manter a atenção plena em leituras e estudos.',
  },
  {
    id: 'music-calm-garden',
    title: 'Jardim calmo',
    artist: 'Respira Instrumental',
    category: 'relax',
    categoryLabel: 'Para relaxar',
    durationMinutes: 6,
    durationSeconds: 360,
    audioUrl: 'https://cdn.pixabay.com/download/audio/2021/09/06/audio_73229b1399.mp3?filename=garden-strings-calm-14284.mp3',
    thumbnailUrl: 'https://images.unsplash.com/photo-1502082553048-f009c37129b9?auto=format&fit=crop&w=600&q=80',
    accentColor: '#4A7A3E',
    description: 'Instrumentação orgânica com violoncelo suave e brisa para soltar a musculatura do corpo.',
  },
  {
    id: 'music-deep-rest',
    title: 'Descanso profundo',
    artist: 'Respira Instrumental',
    category: 'sleep',
    categoryLabel: 'Para dormir',
    durationMinutes: 12,
    durationSeconds: 720,
    audioUrl: 'https://cdn.pixabay.com/download/audio/2022/11/06/audio_7314227f2c.mp3?filename=deep-sleep-pad-2345.mp3',
    thumbnailUrl: 'https://images.unsplash.com/photo-1511497584788-87676104235f?auto=format&fit=crop&w=600&q=80',
    accentColor: '#1F2E3B',
    description: 'Faixa longa em tempo lento com notas sustentadas para conduzir ao sono reparador.',
  },
  {
    id: 'music-present-moment',
    title: 'Instante presente',
    artist: 'Respira Instrumental',
    category: 'pause',
    categoryLabel: 'Para uma pausa',
    durationMinutes: 5,
    durationSeconds: 300,
    audioUrl: 'https://cdn.pixabay.com/download/audio/2022/03/10/audio_511993425a.mp3?filename=mindful-harp-bells-11234.mp3',
    thumbnailUrl: 'https://images.unsplash.com/photo-1518241353330-0f7941c2d9b5?auto=format&fit=crop&w=600&q=80',
    accentColor: '#2F7F7C',
    description: 'Sinos suaves e harpa delicada para ancorar a mente no aqui e agora durante o dia.',
  },
  {
    id: 'music-rain-and-piano',
    title: 'Chuva e piano',
    artist: 'Respira Instrumental',
    category: 'relax',
    categoryLabel: 'Para relaxar',
    durationMinutes: 8,
    durationSeconds: 480,
    audioUrl: 'https://cdn.pixabay.com/download/audio/2022/05/16/audio_c9769ee80a.mp3?filename=piano-rain-harmony-111154.mp3',
    thumbnailUrl: 'https://images.unsplash.com/photo-1519692933481-e162a57d6721?auto=format&fit=crop&w=600&q=80',
    accentColor: '#366B7C',
    description: 'Combinação reconfortante de pingos suaves de chuva com melodia minimalista de piano.',
  },
  {
    id: 'music-calm-waves',
    title: 'Ondas tranquilas',
    artist: 'Respira Instrumental',
    category: 'decelerate',
    categoryLabel: 'Para desacelerar',
    durationMinutes: 7,
    durationSeconds: 420,
    audioUrl: 'https://cdn.pixabay.com/download/audio/2022/01/18/audio_d0a13f69d2.mp3?filename=waves-ambient-guitar-8167.mp3',
    thumbnailUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80',
    accentColor: '#2C648E',
    description: 'Som distante do oceano harmonizado com violão em tempo adágio para soltar tensões.',
  },
];
