import { MusicTrack } from '../types';

export const MUSIC_TRACKS: MusicTrack[] = [
  // =========================================================================
  // PARA RELAXAR (1 a 6)
  // =========================================================================
  {
    id: 'music-caminho-sereno',
    title: 'Caminho sereno',
    artist: 'Respira Instrumental',
    category: 'relax',
    categoryLabel: 'Para relaxar',
    durationMinutes: 5,
    durationSeconds: 330,
    audioUrl: 'https://cdn.pixabay.com/download/audio/2022/05/16/audio_c9769ee80a.mp3?filename=soft-ambient-pad-12345.mp3',
    thumbnailUrl: 'https://images.unsplash.com/photo-1470240731273-7821a6eeb6bd?auto=format&fit=crop&w=600&q=80',
    accentColor: '#2F7F7C',
    description: 'Melodia relaxante de cordas e sintetizadores sutis para aliviar o peso de um dia agitado.',
  },
  {
    id: 'music-pausa-para-respirar',
    title: 'Pausa para respirar',
    artist: 'Respira Instrumental',
    category: 'relax',
    categoryLabel: 'Para relaxar',
    durationMinutes: 4,
    durationSeconds: 255,
    audioUrl: 'https://cdn.pixabay.com/download/audio/2022/01/18/audio_d0a13f69d2.mp3?filename=gentle-acoustic-guitar-7890.mp3',
    thumbnailUrl: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=600&q=80',
    accentColor: '#3B7A57',
    description: 'Arpejos leves de violão acústico para fazer uma pausa de poucos minutos e renovar o ânimo.',
  },
  {
    id: 'music-jardim-silencioso',
    title: 'Jardim silencioso',
    artist: 'Respira Instrumental',
    category: 'relax',
    categoryLabel: 'Para relaxar',
    durationMinutes: 6,
    durationSeconds: 380,
    audioUrl: 'https://cdn.pixabay.com/download/audio/2021/09/06/audio_73229b1399.mp3?filename=garden-strings-calm-14284.mp3',
    thumbnailUrl: 'https://images.unsplash.com/photo-1502082553048-f009c37129b9?auto=format&fit=crop&w=600&q=80',
    accentColor: '#4A7A3E',
    description: 'Instrumentação orgânica com violoncelo suave e brisa para soltar a musculatura do corpo.',
  },
  {
    id: 'music-brisa-tranquila',
    title: 'Brisa tranquila',
    artist: 'Respira Instrumental',
    category: 'relax',
    categoryLabel: 'Para relaxar',
    durationMinutes: 5,
    durationSeconds: 345,
    audioUrl: 'https://cdn.pixabay.com/download/audio/2022/03/10/audio_511993425a.mp3?filename=soft-breeze-strings-11234.mp3',
    thumbnailUrl: 'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=600&q=80',
    accentColor: '#6B8E89',
    description: 'Corrente sonora aveludada transmitindo sensação de vastidão, frescor e calma.',
  },
  {
    id: 'music-horizonte-calmo',
    title: 'Horizonte calmo',
    artist: 'Respira Instrumental',
    category: 'relax',
    categoryLabel: 'Para relaxar',
    durationMinutes: 6,
    durationSeconds: 370,
    audioUrl: 'https://cdn.pixabay.com/download/audio/2021/08/04/audio_32b03657b9.mp3?filename=calm-horizon-ambient-6543.mp3',
    thumbnailUrl: 'https://images.unsplash.com/photo-1495616811223-4d98c6e9c869?auto=format&fit=crop&w=600&q=80',
    accentColor: '#2C648E',
    description: 'Harmonias amplas e inspiradoras que desaceleram a mente e trazem clareza.',
  },
  {
    id: 'music-tarde-de-paz',
    title: 'Tarde de paz',
    artist: 'Respira Instrumental',
    category: 'relax',
    categoryLabel: 'Para relaxar',
    durationMinutes: 4,
    durationSeconds: 290,
    audioUrl: 'https://cdn.pixabay.com/download/audio/2022/01/18/audio_84a56c4d81.mp3?filename=peaceful-afternoon-acoustic-8321.mp3',
    thumbnailUrl: 'https://images.unsplash.com/photo-1518495973542-4542c06a5843?auto=format&fit=crop&w=600&q=80',
    accentColor: '#D98968',
    description: 'Acordes quentes de violão e luz dourada para acolher o fim da tarde com tranquilidade.',
  },

  // =========================================================================
  // PARA DORMIR (7 a 12)
  // =========================================================================
  {
    id: 'music-noite-tranquila',
    title: 'Noite tranquila',
    artist: 'Respira Instrumental',
    category: 'sleep',
    categoryLabel: 'Para dormir',
    durationMinutes: 8,
    durationSeconds: 510,
    audioUrl: 'https://cdn.pixabay.com/download/audio/2022/04/27/audio_93818f9cf0.mp3?filename=ambient-pad-serenity-110294.mp3',
    thumbnailUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=600&q=80',
    accentColor: '#2B3D54',
    description: 'Camadas harmônicas suaves e etéreas que diminuem o ritmo cardíaco e preparam para o descanso.',
  },
  {
    id: 'music-ceu-noturno',
    title: 'Céu noturno',
    artist: 'Respira Instrumental',
    category: 'sleep',
    categoryLabel: 'Para dormir',
    durationMinutes: 9,
    durationSeconds: 555,
    audioUrl: 'https://cdn.pixabay.com/download/audio/2022/03/15/audio_c3c3a9926e.mp3?filename=night-sky-meditation-10925.mp3',
    thumbnailUrl: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=600&q=80',
    accentColor: '#1F2E3B',
    description: 'Sons lentos e reverberações cósmicas que guiam a mente para um estado de repouso absoluto.',
  },
  {
    id: 'music-sono-profundo',
    title: 'Sono profundo',
    artist: 'Respira Instrumental',
    category: 'sleep',
    categoryLabel: 'Para dormir',
    durationMinutes: 12,
    durationSeconds: 720,
    audioUrl: 'https://cdn.pixabay.com/download/audio/2022/11/06/audio_7314227f2c.mp3?filename=deep-sleep-pad-2345.mp3',
    thumbnailUrl: 'https://images.unsplash.com/photo-1511497584788-87676104235f?auto=format&fit=crop&w=600&q=80',
    accentColor: '#17232F',
    description: 'Faixa longa em tempo adágio com notas sustentadas para induzir ao sono reparador.',
  },
  {
    id: 'music-luz-da-lua',
    title: 'Luz da lua',
    artist: 'Respira Instrumental',
    category: 'sleep',
    categoryLabel: 'Para dormir',
    durationMinutes: 7,
    durationSeconds: 440,
    audioUrl: 'https://cdn.pixabay.com/download/audio/2022/08/02/audio_884d6b6379.mp3?filename=moonlight-piano-soft-11234.mp3',
    thumbnailUrl: 'https://images.unsplash.com/photo-1532767153582-b1a0e5145009?auto=format&fit=crop&w=600&q=80',
    accentColor: '#3A4B60',
    description: 'Piano solo minimalista sob o brilho da lua para embalar os pensamentos em serenidade.',
  },
  {
    id: 'music-silencio-da-madrugada',
    title: 'Silêncio da madrugada',
    artist: 'Respira Instrumental',
    category: 'sleep',
    categoryLabel: 'Para dormir',
    durationMinutes: 10,
    durationSeconds: 640,
    audioUrl: 'https://cdn.pixabay.com/download/audio/2022/01/18/audio_145d2f3473.mp3?filename=midnight-silence-drone-8123.mp3',
    thumbnailUrl: 'https://images.unsplash.com/photo-1488866022504-f2584929ca5f?auto=format&fit=crop&w=600&q=80',
    accentColor: '#192734',
    description: 'Vácuo sonoro envolvente e harmonias subterrâneas que silenciam qualquer agitação mental.',
  },
  {
    id: 'music-nuvens-lentas',
    title: 'Nuvens lentas',
    artist: 'Respira Instrumental',
    category: 'sleep',
    categoryLabel: 'Para dormir',
    durationMinutes: 8,
    durationSeconds: 480,
    audioUrl: 'https://cdn.pixabay.com/download/audio/2022/10/18/audio_651296230f.mp3?filename=slow-clouds-ambient-2451.mp3',
    thumbnailUrl: 'https://images.unsplash.com/photo-1500491460312-c32fc2dbc751?auto=format&fit=crop&w=600&q=80',
    accentColor: '#4A6273',
    description: 'Textura sonora flutuante que simula a passagem mansa das nuvens pelo céu noturno.',
  },

  // =========================================================================
  // PARA MEDITAR (13 a 18)
  // =========================================================================
  {
    id: 'music-piano-ao-amanhecer',
    title: 'Piano ao amanhecer',
    artist: 'Respira Instrumental',
    category: 'meditate',
    categoryLabel: 'Para meditar',
    durationMinutes: 5,
    durationSeconds: 345,
    audioUrl: 'https://cdn.pixabay.com/download/audio/2022/01/18/audio_7240c9f131.mp3?filename=gentle-piano-calm-6893.mp3',
    thumbnailUrl: 'https://images.unsplash.com/photo-1520523839898-50712825d3a3?auto=format&fit=crop&w=600&q=80',
    accentColor: '#4A6B82',
    description: 'Acordes serenos e compassados de piano acústico para abrir o dia com clareza e presença.',
  },
  {
    id: 'music-presenca',
    title: 'Presença',
    artist: 'Respira Instrumental',
    category: 'meditate',
    categoryLabel: 'Para meditar',
    durationMinutes: 6,
    durationSeconds: 390,
    audioUrl: 'https://cdn.pixabay.com/download/audio/2022/03/15/audio_247e112d8a.mp3?filename=mindful-presence-zen-10924.mp3',
    thumbnailUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80',
    accentColor: '#2F7F7C',
    description: 'Flauta zen e ressonância de sino tibetano para ancorar a atenção no momento presente.',
  },
  {
    id: 'music-instante-de-calma',
    title: 'Instante de calma',
    artist: 'Respira Instrumental',
    category: 'meditate',
    categoryLabel: 'Para meditar',
    durationMinutes: 5,
    durationSeconds: 315,
    audioUrl: 'https://cdn.pixabay.com/download/audio/2021/08/09/audio_65cf11f8b4.mp3?filename=moment-of-calm-harp-7890.mp3',
    thumbnailUrl: 'https://images.unsplash.com/photo-1518241353330-0f7941c2d9b5?auto=format&fit=crop&w=600&q=80',
    accentColor: '#3B6B7C',
    description: 'Harpa delicada combinada a sintetizadores contemplativos para silenciar ruídos externos.',
  },
  {
    id: 'music-respiracao-consciente',
    title: 'Respiração consciente',
    artist: 'Respira Instrumental',
    category: 'meditate',
    categoryLabel: 'Para meditar',
    durationMinutes: 7,
    durationSeconds: 420,
    audioUrl: 'https://cdn.pixabay.com/download/audio/2022/06/15/audio_24e931e289.mp3?filename=mindful-breathing-pad-5432.mp3',
    thumbnailUrl: 'https://images.unsplash.com/photo-1545205597-3d9d02c29597?auto=format&fit=crop&w=600&q=80',
    accentColor: '#247B74',
    description: 'Pulsação rítmica sutil para guiar ciclos respiratórios profundos e conscientes.',
  },
  {
    id: 'music-equilibrio-interior',
    title: 'Equilíbrio interior',
    artist: 'Respira Instrumental',
    category: 'meditate',
    categoryLabel: 'Para meditar',
    durationMinutes: 6,
    durationSeconds: 405,
    audioUrl: 'https://cdn.pixabay.com/download/audio/2022/10/14/audio_993e506699.mp3?filename=inner-balance-strings-1234.mp3',
    thumbnailUrl: 'https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=600&q=80',
    accentColor: '#5B8C5A',
    description: 'Harmonias de violoncelo e tigela de cristal para harmonizar corpo, mente e respiração.',
  },
  {
    id: 'music-som-do-presente',
    title: 'Som do presente',
    artist: 'Respira Instrumental',
    category: 'meditate',
    categoryLabel: 'Para meditar',
    durationMinutes: 5,
    durationSeconds: 350,
    audioUrl: 'https://cdn.pixabay.com/download/audio/2022/05/16/audio_276a6cf43a.mp3?filename=sound-of-now-chimes-9876.mp3',
    thumbnailUrl: 'https://images.unsplash.com/photo-1432405972618-c60b0225b8f9?auto=format&fit=crop&w=600&q=80',
    accentColor: '#1E6B8A',
    description: 'Sinos de vento e cordas dedilhadas proporcionando profundo recolhimento espiritual.',
  },

  // =========================================================================
  // PARA ESTUDAR (19 a 24)
  // =========================================================================
  {
    id: 'music-foco-leve',
    title: 'Foco leve',
    artist: 'Respira Instrumental',
    category: 'study',
    categoryLabel: 'Para estudar',
    durationMinutes: 6,
    durationSeconds: 360,
    audioUrl: 'https://cdn.pixabay.com/download/audio/2022/03/10/audio_511993425b.mp3?filename=light-focus-rhodes-11235.mp3',
    thumbnailUrl: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&w=600&q=80',
    accentColor: '#7A6248',
    description: 'Cadência leve em teclado Rhodes e batida lo-fi suave para manter a concentração contínua.',
  },
  {
    id: 'music-concentracao-serena',
    title: 'Concentração serena',
    artist: 'Respira Instrumental',
    category: 'study',
    categoryLabel: 'Para estudar',
    durationMinutes: 8,
    durationSeconds: 500,
    audioUrl: 'https://cdn.pixabay.com/download/audio/2022/01/18/audio_d0a13f69d3.mp3?filename=serene-concentration-lofi-8168.mp3',
    thumbnailUrl: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?auto=format&fit=crop&w=600&q=80',
    accentColor: '#534666',
    description: 'Ambiente acústico contínuo e sem distrações vocais para estudos longos e produtivos.',
  },
  {
    id: 'music-piano-para-estudar',
    title: 'Piano para estudar',
    artist: 'Respira Instrumental',
    category: 'study',
    categoryLabel: 'Para estudar',
    durationMinutes: 7,
    durationSeconds: 430,
    audioUrl: 'https://cdn.pixabay.com/download/audio/2022/05/16/audio_c9769ee80b.mp3?filename=study-piano-cadence-111155.mp3',
    thumbnailUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=600&q=80',
    accentColor: '#3A506B',
    description: 'Piano neoclássico cadenciado e harmonioso que estimula o raciocínio sem cansar a mente.',
  },
  {
    id: 'music-fluxo-continuo',
    title: 'Fluxo contínuo',
    artist: 'Respira Instrumental',
    category: 'study',
    categoryLabel: 'Para estudar',
    durationMinutes: 9,
    durationSeconds: 540,
    audioUrl: 'https://cdn.pixabay.com/download/audio/2022/04/27/audio_93818f9cf1.mp3?filename=steady-flow-synth-110295.mp3',
    thumbnailUrl: 'https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?auto=format&fit=crop&w=600&q=80',
    accentColor: '#2F5D62',
    description: 'Arpejos analógicos e texturas rítmicas suaves para entrar no estado de flow mental.',
  },
  {
    id: 'music-mente-organizada',
    title: 'Mente organizada',
    artist: 'Respira Instrumental',
    category: 'study',
    categoryLabel: 'Para estudar',
    durationMinutes: 6,
    durationSeconds: 390,
    audioUrl: 'https://cdn.pixabay.com/download/audio/2022/10/18/audio_651296231a.mp3?filename=organized-mind-marimba-2452.mp3',
    thumbnailUrl: 'https://images.unsplash.com/photo-1499750310107-5fef28a66643?auto=format&fit=crop&w=600&q=80',
    accentColor: '#634E99',
    description: 'Notas pontuais de marimba e cordas rítmicas discretas para organização e produtividade.',
  },
  {
    id: 'music-leitura-tranquila',
    title: 'Leitura tranquila',
    artist: 'Respira Instrumental',
    category: 'study',
    categoryLabel: 'Para estudar',
    durationMinutes: 5,
    durationSeconds: 340,
    audioUrl: 'https://cdn.pixabay.com/download/audio/2022/11/06/audio_7314227f2d.mp3?filename=quiet-reading-guitar-2346.mp3',
    thumbnailUrl: 'https://images.unsplash.com/photo-1457369804613-52c61a468e7d?auto=format&fit=crop&w=600&q=80',
    accentColor: '#7A5B44',
    description: 'Violão clássico dedilhado com ambiência suave, perfeito para livros e artigos.',
  },
];
